apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: helm-deploy-mysql-
spec:
  serviceAccountName: argo
  entrypoint: helm-deploy
  arguments:
    parameters:
      # set to your repo
      - name: repo-url
        value: "https://github.com/Devopsguru4d/argo-devops-project.git"
      # where the chart lives inside the repo (relative to repo root)
      - name: chart-subpath
        value: "mysql"
      # optional branch/tag/commit (empty = default branch)
      - name: revision
        value: ""
      # pin a known-good Bitnami MySQL image (9.4.0 tags were 404)
      - name: image-repository
        value: "docker.io/bitnami/mysql"
      - name: image-tag
        value: "8.4.0-debian-12-r1"

  # Persist workspace across pods/steps
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: helm-deploy
      steps:
        - - name: check-release
            template: check-release
        - - name: clone-repo
            template: clone-repo
            arguments:
              parameters:
                - name: repo-url
                  value: "{{workflow.parameters.repo-url}}"
                - name: revision
                  value: "{{workflow.parameters.revision}}"
        - - name: install-or-upgrade
            template: install-or-upgrade
            arguments:
              parameters:
                - name: release-status
                  value: "{{steps.check-release.outputs.parameters.release-status}}"
                - name: chart-subpath
                  value: "{{workflow.parameters.chart-subpath}}"
                - name: image-repository
                  value: "{{workflow.parameters.image-repository}}"
                - name: image-tag
                  value: "{{workflow.parameters.image-tag}}"

    - name: check-release
      script:
        image: alpine:3.20
        command: ["/bin/sh","-euo","pipefail","-c"]
        source: |
          apk add --no-cache curl tar
          HELM_VER=v3.15.3
          case "$(uname -m)" in
            aarch64|arm64) A=arm64 ;;
            x86_64|amd64)  A=amd64 ;;
            *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
          esac
          curl -sSL "https://get.helm.sh/helm-${HELM_VER}-linux-${A}.tar.gz" -o /tmp/helm.tgz
          tar -xzf /tmp/helm.tgz -C /tmp
          install -m0755 "/tmp/linux-${A}/helm" /usr/local/bin/helm

          if helm status mysql -n app >/dev/null 2>&1; then
            echo installed >/tmp/out
          else
            echo not-installed >/tmp/out
          fi
      outputs:
        parameters:
          - name: release-status
            valueFrom:
              path: /tmp/out

    - name: clone-repo
      inputs:
        parameters:
          - name: repo-url
          - name: revision
      script:
        image: alpine:3.20
        command: ["/bin/sh","-euo","pipefail","-c"]
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        source: |
          apk add --no-cache git
          rm -rf /workspace/* || true
          if [ -n "{{inputs.parameters.revision}}" ]; then
            git clone --depth=1 --branch "{{inputs.parameters.revision}}" "{{inputs.parameters.repo-url}}" /workspace
          else
            git clone --depth=1 "{{inputs.parameters.repo-url}}" /workspace
          fi
          echo "Repo cloned. Root:"
          ls -la /workspace

    - name: install-or-upgrade
      inputs:
        parameters:
          - name: release-status
          - name: chart-subpath
          - name: image-repository
          - name: image-tag
      script:
        image: alpine:3.20
        command: ["/bin/sh","-euo","pipefail","-c"]
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        source: |
          apk add --no-cache curl tar findutils
          HELM_VER=v3.15.3
          case "$(uname -m)" in
            aarch64|arm64) A=arm64 ;;
            x86_64|amd64)  A=amd64 ;;
            *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
          esac
          curl -sSL "https://get.helm.sh/helm-${HELM_VER}-linux-${A}.tar.gz" -o /tmp/helm.tgz
          tar -xzf /tmp/helm.tgz -C /tmp
          install -m0755 "/tmp/linux-${A}/helm" /usr/local/bin/helm

          CHART_PATH="/workspace/{{inputs.parameters.chart-subpath}}"
          if [ ! -f "$CHART_PATH/Chart.yaml" ]; then
            echo "Configured chart path '$CHART_PATH' missing, auto-detecting..."
            DETECTED="$(find /workspace -maxdepth 3 -type f -name Chart.yaml | head -n1 || true)"
            [ -n "$DETECTED" ] || { echo "No Chart.yaml found under /workspace"; exit 1; }
            CHART_PATH="$(dirname "$DETECTED")"
            echo "Detected chart at: $CHART_PATH"
          fi

          echo "Release status is: {{inputs.parameters.release-status}}"
          if [ "{{inputs.parameters.release-status}}" = "not-installed" ]; then
            echo "Installing MySQL..."
            helm install mysql "$CHART_PATH" -n app --create-namespace \
              --set image.repository="{{inputs.parameters.image-repository}}" \
              --set image.tag="{{inputs.parameters.image-tag}}"
          else
            echo "Upgrading MySQL..."
            helm upgrade mysql "$CHART_PATH" -n app \
              --set image.repository="{{inputs.parameters.image-repository}}" \
              --set image.tag="{{inputs.parameters.image-tag}}"
          fi
